#!/bin/bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
out_file="$script_dir/reset_tmux.conf"
tmp_file=$(mktemp)
trap 'rm -f "$tmp_file"' EXIT

# See https://unix.stackexchange.com/a/255343
tmux -f /dev/null -L temp start-server \; list-keys |
    sed -r \
        -e "s/bind-key(\s+)([\"#~\$])(\s+)/bind-key\1\'\2\'\3/g" \
        -e "s/bind-key(\s+)([\'])(\s+)/bind-key\1\"\2\"\3/g" \
        -e "s/bind-key(\s+)([;])(\s+)/bind-key\1\\\\\2\3/g" \
        -e "s/command-prompt -I #([SW])/command-prompt -I \"#\1\"/g" \
        >"$tmp_file"

{
    printf '### This file was autogenerated by `reset_tmux.sh`. Do NOT edit it directly.\n'
    printf '### See https://unix.stackexchange.com/a/255343\n\n'
    cat "$tmp_file"
} >"$out_file"
