#!/bin/bash

# See https://unix.stackexchange.com/a/255343
tmux -f /dev/null -L temp start-server \; list-keys |
    sed -r \
        -e "s/bind-key(\s+)([\"#~\$])(\s+)/bind-key\1\'\2\'\3/g" \
        -e "s/bind-key(\s+)([\'])(\s+)/bind-key\1\"\2\"\3/g" \
        -e "s/bind-key(\s+)([;])(\s+)/bind-key\1\\\\\2\3/g" \
        -e "s/command-prompt -I #([SW])/command-prompt -I \"#\1\"/g" \
        >reset_tmux.conf

sed -i '1s|^|### This file was autogenerated by `reset_tmux.sh`. Do not edit it directly!\n### See https://unix.stackexchange.com/a/255343\n\n|' reset_tmux.conf
