# See https://github.com/dwmkerr/dotfiles/blob/main/tmux/tmux.conf

# Reset all keybindings
# See https://unix.stackexchange.com/a/255343
unbind-key -a
source-file ~/.config/tmux/reset_tmux.conf

# Reload the tmux config with a keybinding
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Enable mouse support
set -g mouse on

# Copy/paste between tmux and system clipboard
set -s set-clipboard on 

# Use 256 colors
set-option -a terminal-features "xterm-256color:RGB"
# set-option -a terminal-overrides ",xterm-256color:Tc"
# set-option -g default-terminal "xterm-256color"

# Remap prefix key
unbind C-b
set-option -g prefix `
bind ` send-prefix

# Open new panes and splits in the same working directory
bind c new-window -c "#{pane_current_path}"

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Split panes using | and -
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Prefix + h/j/k/l to move through panes
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# Prefix + Ctrl-h/j/k/l to resize panes
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "nordtheme/tmux"
set -g @nord_tmux_show_status_content "0" # Use the custom status bar

# Missing colors in Nord theme
set-option -g message-style "fg=cyan,bg=brightblack"
set-option -g message-command-style "fg=blue,bg=black"
set-option -g copy-mode-match-style "fg=white,bg=#5E81AC"
set-option -g copy-mode-mark-style "fg=white,bg=#5E81AC"
set-option -g copy-mode-current-match-style "fg=white,bg=cyan"
set-option -g mode-style "fg=cyan,bg=brightblack"

# See https://github.com/nordtheme/tmux/blob/develop/src/nord-status-content-no-patched-font.conf
# Left/right side of status line
set -g status-style "bg=black"
set -g status-left ""
# Use TZ='Etc/GMT+6' since TZ='America/Mexico_City' uses Daylight Saving Time on some Linux distros
set -g status-right "#[fg=white,bg=black] #(TZ='Etc/GMT+6' date '+%%a %%d %b | %%H:%%M') "

# Window list in status line
set -g window-status-format " #[fg=white,bg=black]#I #W #F"
set -g window-status-current-format " #[fg=black,bg=blue]#I #W #F"
set -g window-status-separator ""

# Pane border
set -g pane-border-style "fg=black"
set -g pane-active-border-style "fg=blue"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
