# This empty file fixes the error:
#   "Your workspace is set to [...]. Lua Language server refused to load this directory."
# See https://github.com/LunarVim/LunarVim/issues/2736#issuecomment-1171080243
